-- ============================================================
-- Kair — Supabase Database Schema
-- Run this in: Supabase Dashboard → SQL Editor
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- PROFILES (extends Supabase auth.users)
-- ============================================================
CREATE TABLE profiles (
  id            UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name     TEXT,
  phone         TEXT UNIQUE,
  role          TEXT NOT NULL DEFAULT 'customer' CHECK (role IN ('customer', 'rider', 'admin')),
  area          TEXT,                          -- e.g. "Koregaon Park"
  city          TEXT DEFAULT 'Pune',
  avatar_url    TEXT,
  language_pref TEXT DEFAULT 'en' CHECK (language_pref IN ('en', 'hi', 'mr')),
  is_active     BOOLEAN DEFAULT TRUE,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO profiles (id, phone)
  VALUES (NEW.id, NEW.phone);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ============================================================
-- SERVICES CATALOGUE
-- ============================================================
CREATE TABLE service_categories (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  slug        TEXT UNIQUE NOT NULL,       -- 'clothes', 'shoes', 'curtains', 'household'
  name_en     TEXT NOT NULL,
  name_hi     TEXT,
  name_mr     TEXT,
  emoji       TEXT,
  sort_order  INT DEFAULT 0,
  is_active   BOOLEAN DEFAULT TRUE
);

CREATE TABLE services (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  category_id   UUID REFERENCES service_categories(id),
  name_en       TEXT NOT NULL,
  name_hi       TEXT,
  name_mr       TEXT,
  description   TEXT,
  price_paise   INT NOT NULL,             -- price in paise (₹1 = 100 paise)
  unit          TEXT NOT NULL,            -- 'per kg', 'per item', 'per pair', 'per panel'
  emoji         TEXT,
  is_active     BOOLEAN DEFAULT TRUE,
  sort_order    INT DEFAULT 0
);

-- ============================================================
-- ADDRESSES
-- ============================================================
CREATE TABLE addresses (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id     UUID REFERENCES profiles(id) ON DELETE CASCADE,
  label       TEXT DEFAULT 'Home',        -- 'Home', 'Work', 'Other'
  flat_no     TEXT,
  building    TEXT,
  area        TEXT NOT NULL,
  landmark    TEXT,
  city        TEXT DEFAULT 'Pune',
  pincode     TEXT,
  lat         DOUBLE PRECISION,
  lng         DOUBLE PRECISION,
  is_default  BOOLEAN DEFAULT FALSE,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- ORDERS
-- ============================================================
CREATE TABLE orders (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_number    TEXT UNIQUE NOT NULL,    -- e.g. KR-2041 (generated by trigger)
  customer_id     UUID REFERENCES profiles(id),
  address_id      UUID REFERENCES addresses(id),
  rider_id        UUID REFERENCES profiles(id),

  status          TEXT NOT NULL DEFAULT 'pending_pickup'
                  CHECK (status IN (
                    'pending_pickup',   -- waiting for rider to collect
                    'rider_assigned',   -- rider on the way
                    'picked_up',        -- rider collected clothes
                    'in_cleaning',      -- at facility
                    'quality_check',    -- QC pass
                    'ready',            -- ready to deliver
                    'out_for_delivery', -- rider heading to customer
                    'delivered',        -- done
                    'cancelled'
                  )),

  payment_method  TEXT CHECK (payment_method IN ('upi', 'card', 'cod', 'netbanking')),
  payment_status  TEXT DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded')),
  razorpay_order_id   TEXT,
  razorpay_payment_id TEXT,

  total_paise     INT DEFAULT 0,          -- final total in paise
  pickup_slot     TEXT,                   -- e.g. '2pm – 4pm'
  pickup_date     DATE,
  special_notes   TEXT,
  language        TEXT DEFAULT 'en',

  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW(),
  picked_up_at    TIMESTAMPTZ,
  delivered_at    TIMESTAMPTZ
);

-- Auto-generate order number (KR-XXXX)
CREATE SEQUENCE order_number_seq START 1001;
CREATE OR REPLACE FUNCTION generate_order_number()
RETURNS TRIGGER AS $$
BEGIN
  NEW.order_number := 'KR-' || nextval('order_number_seq');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_order_number
  BEFORE INSERT ON orders
  FOR EACH ROW EXECUTE FUNCTION generate_order_number();

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- ORDER ITEMS
-- ============================================================
CREATE TABLE order_items (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id    UUID REFERENCES orders(id) ON DELETE CASCADE,
  service_id  UUID REFERENCES services(id),
  service_name TEXT NOT NULL,             -- snapshot at time of order
  quantity    INT NOT NULL DEFAULT 1,
  price_paise INT NOT NULL,               -- price per unit at time of order
  subtotal_paise INT GENERATED ALWAYS AS (quantity * price_paise) STORED
);

-- ============================================================
-- GARMENT TAGS (individual item tracking per order)
-- ============================================================
CREATE TABLE garment_tags (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id    UUID REFERENCES orders(id) ON DELETE CASCADE,
  order_item_id UUID REFERENCES order_items(id),
  tag_code    TEXT NOT NULL,              -- e.g. KR-2041-01
  item_name   TEXT NOT NULL,             -- e.g. "Shirt / Blouse"
  status      TEXT NOT NULL DEFAULT 'received'
              CHECK (status IN (
                'received',
                'sorting',
                'in_cleaning',
                'drying',
                'pressed',
                'quality_check',
                'ready',
                'packed'
              )),
  notes       TEXT,
  updated_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_by  UUID REFERENCES profiles(id)
);

-- ============================================================
-- ORDER STATUS HISTORY (full audit trail)
-- ============================================================
CREATE TABLE order_status_history (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id    UUID REFERENCES orders(id) ON DELETE CASCADE,
  old_status  TEXT,
  new_status  TEXT NOT NULL,
  changed_by  UUID REFERENCES profiles(id),
  notes       TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-log status changes
CREATE OR REPLACE FUNCTION log_order_status_change()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.status IS DISTINCT FROM NEW.status THEN
    INSERT INTO order_status_history (order_id, old_status, new_status, changed_by)
    VALUES (NEW.id, OLD.status, NEW.status, auth.uid());
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER order_status_changed
  AFTER UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION log_order_status_change();

-- ============================================================
-- PAYMENTS
-- ============================================================
CREATE TABLE payments (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id            UUID REFERENCES orders(id),
  razorpay_order_id   TEXT,
  razorpay_payment_id TEXT,
  razorpay_signature  TEXT,
  amount_paise        INT NOT NULL,
  currency            TEXT DEFAULT 'INR',
  method              TEXT,               -- 'upi', 'card', 'cod', etc.
  status              TEXT DEFAULT 'created',
  captured_at         TIMESTAMPTZ,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- RIDER LOCATIONS (realtime tracking)
-- ============================================================
CREATE TABLE rider_locations (
  rider_id    UUID PRIMARY KEY REFERENCES profiles(id),
  lat         DOUBLE PRECISION,
  lng         DOUBLE PRECISION,
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================

ALTER TABLE profiles          ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders            ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items       ENABLE ROW LEVEL SECURITY;
ALTER TABLE garment_tags      ENABLE ROW LEVEL SECURITY;
ALTER TABLE addresses         ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments          ENABLE ROW LEVEL SECURITY;
ALTER TABLE rider_locations   ENABLE ROW LEVEL SECURITY;

-- Profiles: users see only their own; admins see all
CREATE POLICY "Users can view own profile"     ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile"   ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins can view all profiles"   ON profiles FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Orders: customers see own orders; riders see assigned; admins see all
CREATE POLICY "Customers view own orders" ON orders FOR SELECT USING (customer_id = auth.uid());
CREATE POLICY "Customers create orders"  ON orders FOR INSERT WITH CHECK (customer_id = auth.uid());
CREATE POLICY "Riders view assigned"     ON orders FOR SELECT USING (rider_id = auth.uid());
CREATE POLICY "Riders update assigned"   ON orders FOR UPDATE USING (rider_id = auth.uid());
CREATE POLICY "Admins full access"       ON orders FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin'))
);

-- Order items: same visibility as parent order
CREATE POLICY "View order items" ON order_items FOR SELECT USING (
  EXISTS (SELECT 1 FROM orders WHERE id = order_id AND (customer_id = auth.uid() OR rider_id = auth.uid()))
);

-- Garment tags: ops team (admin) full access; customers read-only for their orders
CREATE POLICY "Customer view tags" ON garment_tags FOR SELECT USING (
  EXISTS (SELECT 1 FROM orders WHERE id = order_id AND customer_id = auth.uid())
);
CREATE POLICY "Admin full tag access" ON garment_tags FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Addresses: own only
CREATE POLICY "Own addresses only" ON addresses FOR ALL USING (user_id = auth.uid());

-- Services: public read
ALTER TABLE services          ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read services"    ON services           FOR SELECT USING (true);
CREATE POLICY "Public read categories"  ON service_categories FOR SELECT USING (true);

-- ============================================================
-- REALTIME (enable for live order tracking)
-- ============================================================
ALTER PUBLICATION supabase_realtime ADD TABLE orders;
ALTER PUBLICATION supabase_realtime ADD TABLE garment_tags;
ALTER PUBLICATION supabase_realtime ADD TABLE rider_locations;

-- ============================================================
-- SEED DATA — Service categories & services
-- ============================================================
INSERT INTO service_categories (slug, name_en, name_hi, name_mr, emoji, sort_order) VALUES
  ('clothes',   'Clothes',   'कपड़े',  'कपडे',  '👕', 1),
  ('shoes',     'Shoes',     'जूते',   'बूट',   '👟', 2),
  ('curtains',  'Curtains',  'पर्दे',  'पडदे',  '🪟', 3),
  ('household', 'Household', 'घरेलू',  'घरगुती','🛏️', 4);

INSERT INTO services (category_id, name_en, name_hi, name_mr, description, price_paise, unit, emoji, sort_order) VALUES
  -- Clothes
  ((SELECT id FROM service_categories WHERE slug='clothes'), 'Wash & Fold',       'वॉश एंड फोल्ड',    'वॉश अँड फोल्ड',    'Machine washed & neatly folded',             4900,  'per kg',    '👕', 1),
  ((SELECT id FROM service_categories WHERE slug='clothes'), 'Wash & Iron',       'वॉश एंड आयरन',     'वॉश अँड इस्त्री',  'Washed, dried and ironed to perfection',     7900,  'per kg',    '👔', 2),
  ((SELECT id FROM service_categories WHERE slug='clothes'), 'Dry Cleaning',      'ड्राई क्लीनिंग',   'ड्राय क्लीनिंग',   'Expert dry cleaning for suits & formals',    14900, 'per item',  '🥼', 3),
  ((SELECT id FROM service_categories WHERE slug='clothes'), 'Jacket / Coat',     'जैकेट / कोट',      'जॅकेट / कोट',      'Heavy outerwear dry cleaned & pressed',      19900, 'per item',  '🧥', 4),
  ((SELECT id FROM service_categories WHERE slug='clothes'), 'Saree / Lehenga',   'साड़ी / लहंगा',    'साडी / लेहंगा',    'Delicate hand-wash for ethnic wear',         12900, 'per item',  '🥻', 5),
  ((SELECT id FROM service_categories WHERE slug='clothes'), 'Denims / Jeans',    'डेनिम / जींस',     'डेनिम / जीन्स',    'Machine wash with deep clean treatment',     5900,  'per piece', '👖', 6),
  -- Shoes
  ((SELECT id FROM service_categories WHERE slug='shoes'), 'Sneaker Deep Clean', 'स्नीकर क्लीन',    'स्नीकर क्लीन',    'Full clean, deodorize & white sole restore', 29900, 'per pair',  '👟', 1),
  ((SELECT id FROM service_categories WHERE slug='shoes'), 'Leather Shoes Polish','लेदर पॉलिश',      'लेदर पॉलिश',      'Clean, condition & mirror polish',           19900, 'per pair',  '👞', 2),
  ((SELECT id FROM service_categories WHERE slug='shoes'), 'Heels / Sandals',    'हील्स / सैंडल',   'हील्स / सँडल',    'Gentle clean & refresh',                    14900, 'per pair',  '👡', 3),
  -- Curtains
  ((SELECT id FROM service_categories WHERE slug='curtains'), 'Curtains – Regular',  'पर्दे - रेगुलर', 'पडदे - रेग्युलर', 'Machine wash, dry & fold',                  9900,  'per panel', '🪟', 1),
  ((SELECT id FROM service_categories WHERE slug='curtains'), 'Curtains – Blackout', 'भारी पर्दे',     'जड पडदे',         'Deep clean & press for thick curtains',      14900, 'per panel', '🎭', 2),
  ((SELECT id FROM service_categories WHERE slug='curtains'), 'Sofa Cover / Cushion','सोफा कवर',       'सोफा कव्हर',      'Wash, dry and refresh',                     12900, 'per piece', '🛋️', 3),
  -- Household
  ((SELECT id FROM service_categories WHERE slug='household'), 'Bedsheet set',    'बेडशीट सेट',     'बेडशीट सेट',     '1 bedsheet + 2 pillow covers',              12900, 'per set',   '🛏️', 1),
  ((SELECT id FROM service_categories WHERE slug='household'), 'Blanket / Duvet', 'कंबल / रजाई',    'ब्लँकेट / रजई',  'Large item deep wash & dry',                24900, 'per piece', '🛁', 2),
  ((SELECT id FROM service_categories WHERE slug='household'), 'Soft toys',       'सॉफ्ट टॉय',      'सॉफ्ट टॉय',      'Gentle wash for soft items',                9900,  'per piece', '🧸', 3),
  ((SELECT id FROM service_categories WHERE slug='household'), 'Bath Towels',     'बाथ टॉवेल',      'बाथ टॉवेल',      'Wash, fresh & fold',                        3900,  'per piece', '🧴', 4);

-- ============================================================
-- DONE! Your database is ready.
-- ============================================================
